#./skimtree dir Hamb mc DoubleMuB.root Mode mHcut 
#./skimtree dir Hamb mc DoubleMuC.root Mode mHcut 
#./skimtree dir Hamb mc DoubleMuD.root Mode mHcut 
#./skimtree dir Hamb mc DoubleMuE.root Mode mHcut 
#./skimtree dir Hamb mc DoubleMuF.root Mode mHcut 
#./skimtree dir Hamb mc DoubleMuG.root Mode mHcut 
#./skimtree dir Hamb mc DoubleMuH2.root Mode mHcut 
#./skimtree dir Hamb mc DoubleMuH3.root Mode mHcut 
#./skimtree dir Hamb mc DYJetsLowMass.root Mode mHcut 
#./skimtree dir Hamb mc DYJets.root Mode mHcut 
#./skimtree dir Hamb mc GGH20.root Mode mHcut 
#./skimtree dir HambPUUp mc GGH20.root Mode mHcut 
#./skimtree dir HambPUDown mc GGH20.root Mode mHcut 
#./skimtree dir HambJECUP mc GGH20.root Mode mHcut 
#./skimtree dir HambJECDOWN mc GGH20.root Mode mHcut 
#./skimtree dir HambJERUP mc GGH20.root Mode mHcut 
#./skimtree dir HambJERDOWN mc GGH20.root Mode mHcut 
#./skimtree dir HambBShape mc GGH20.root Mode mHcut 
#./skimtree dir HambMETUnClusDOWN mc GGH20.root Mode mHcut 
#./skimtree dir HambMETUnClusUP mc GGH20.root Mode mHcut 
#./skimtree dir HambHLTUP mc GGH20.root Mode mHcut 
#./skimtree dir HambHLTDOWN mc GGH20.root Mode mHcut 
#./skimtree dir Hamb mc GGH25.root Mode mHcut 
#./skimtree dir HambPUUp mc GGH25.root Mode mHcut 
#./skimtree dir HambPUDown mc GGH25.root Mode mHcut 
#./skimtree dir HambJECUP mc GGH25.root Mode mHcut 
#./skimtree dir HambJECDOWN mc GGH25.root Mode mHcut 
#./skimtree dir HambJERUP mc GGH25.root Mode mHcut 
#./skimtree dir HambJERDOWN mc GGH25.root Mode mHcut 
#./skimtree dir HambBShape mc GGH25.root Mode mHcut 
#./skimtree dir HambMETUnClusDOWN mc GGH25.root Mode mHcut 
#./skimtree dir HambMETUnClusUP mc GGH25.root Mode mHcut 
#./skimtree dir HambHLTUP mc GGH25.root Mode mHcut 
#./skimtree dir HambHLTDOWN mc GGH25.root Mode mHcut 
#./skimtree dir Hamb mc GGH30.root Mode mHcut 
#./skimtree dir HambPUUp mc GGH30.root Mode mHcut 
#./skimtree dir HambPUDown mc GGH30.root Mode mHcut 
#./skimtree dir HambJECUP mc GGH30.root Mode mHcut 
#./skimtree dir HambJECDOWN mc GGH30.root Mode mHcut 
#./skimtree dir HambJERUP mc GGH30.root Mode mHcut 
#./skimtree dir HambJERDOWN mc GGH30.root Mode mHcut 
#./skimtree dir HambBShape mc GGH30.root Mode mHcut 
#./skimtree dir HambMETUnClusDOWN mc GGH30.root Mode mHcut 
#./skimtree dir HambMETUnClusUP mc GGH30.root Mode mHcut 
#./skimtree dir HambHLTUP mc GGH30.root Mode mHcut 
#./skimtree dir HambHLTDOWN mc GGH30.root Mode mHcut 
#./skimtree dir Hamb mc GGH35.root Mode mHcut 
#./skimtree dir Hamb mc GGH40.root Mode mHcut 
#./skimtree dir HambPUUp mc GGH40.root Mode mHcut 
#./skimtree dir HambPUDown mc GGH40.root Mode mHcut 
#./skimtree dir HambJECUP mc GGH40.root Mode mHcut 
#./skimtree dir HambJECDOWN mc GGH40.root Mode mHcut 
#./skimtree dir HambJERUP mc GGH40.root Mode mHcut 
#./skimtree dir HambJERDOWN mc GGH40.root Mode mHcut 
#./skimtree dir HambBShape mc GGH40.root Mode mHcut 
#./skimtree dir HambMETUnClusDOWN mc GGH40.root Mode mHcut 
#./skimtree dir HambMETUnClusUP mc GGH40.root Mode mHcut 
#./skimtree dir HambHLTUP mc GGH40.root Mode mHcut 
#./skimtree dir HambHLTDOWN mc GGH40.root Mode mHcut 
#./skimtree dir Hamb mc GGH45.root Mode mHcut 
#./skimtree dir HambPUUp mc GGH45.root Mode mHcut 
#./skimtree dir HambPUDown mc GGH45.root Mode mHcut 
#./skimtree dir HambJECUP mc GGH45.root Mode mHcut 
#./skimtree dir HambJECDOWN mc GGH45.root Mode mHcut 
#./skimtree dir HambJERUP mc GGH45.root Mode mHcut 
#./skimtree dir HambJERDOWN mc GGH45.root Mode mHcut 
#./skimtree dir HambBShape mc GGH45.root Mode mHcut 
#./skimtree dir HambMETUnClusDOWN mc GGH45.root Mode mHcut 
#./skimtree dir HambMETUnClusUP mc GGH45.root Mode mHcut 
#./skimtree dir HambHLTUP mc GGH45.root Mode mHcut 
#./skimtree dir HambHLTDOWN mc GGH45.root Mode mHcut 
#./skimtree dir Hamb mc GGH50.root Mode mHcut 
#./skimtree dir HambPUUp mc GGH50.root Mode mHcut 
#./skimtree dir HambPUDown mc GGH50.root Mode mHcut 
#./skimtree dir HambJECUP mc GGH50.root Mode mHcut 
#./skimtree dir HambJECDOWN mc GGH50.root Mode mHcut 
#./skimtree dir HambJERUP mc GGH50.root Mode mHcut 
#./skimtree dir HambJERDOWN mc GGH50.root Mode mHcut 
#./skimtree dir HambBShape mc GGH50.root Mode mHcut 
#./skimtree dir HambMETUnClusDOWN mc GGH50.root Mode mHcut 
#./skimtree dir HambMETUnClusUP mc GGH50.root Mode mHcut 
#./skimtree dir HambHLTUP mc GGH50.root Mode mHcut 
#./skimtree dir HambHLTDOWN mc GGH50.root Mode mHcut 
#./skimtree dir Hamb mc GGH55.root Mode mHcut 
#./skimtree dir HambPUUp mc GGH55.root Mode mHcut 
#./skimtree dir HambPUDown mc GGH55.root Mode mHcut 
#./skimtree dir HambJECUP mc GGH55.root Mode mHcut 
#./skimtree dir HambJECDOWN mc GGH55.root Mode mHcut 
#./skimtree dir HambJERUP mc GGH55.root Mode mHcut 
#./skimtree dir HambJERDOWN mc GGH55.root Mode mHcut 
#./skimtree dir HambBShape mc GGH55.root Mode mHcut 
#./skimtree dir HambMETUnClusDOWN mc GGH55.root Mode mHcut 
#./skimtree dir HambMETUnClusUP mc GGH55.root Mode mHcut 
#./skimtree dir HambHLTUP mc GGH55.root Mode mHcut 
#./skimtree dir HambHLTDOWN mc GGH55.root Mode mHcut 
#./skimtree dir Hamb mc GGH60.root Mode mHcut 
#./skimtree dir HambPUUp mc GGH60.root Mode mHcut 
#./skimtree dir HambPUDown mc GGH60.root Mode mHcut 
#./skimtree dir HambJECUP mc GGH60.root Mode mHcut 
#./skimtree dir HambJECDOWN mc GGH60.root Mode mHcut 
#./skimtree dir HambJERUP mc GGH60.root Mode mHcut 
#./skimtree dir HambJERDOWN mc GGH60.root Mode mHcut 
#./skimtree dir HambBShape mc GGH60.root Mode mHcut 
#./skimtree dir HambMETUnClusDOWN mc GGH60.root Mode mHcut 
#./skimtree dir HambMETUnClusUP mc GGH60.root Mode mHcut 
#./skimtree dir HambHLTUP mc GGH60.root Mode mHcut 
#./skimtree dir HambHLTDOWN mc GGH60.root Mode mHcut 
#./skimtree dir Hamb mc TbarW.root Mode mHcut 
#./skimtree dir Hamb mc TChannelT.root Mode mHcut 
#./skimtree dir Hamb mc TChannelTbar.root Mode mHcut 
#./skimtree dir Hamb mc TTbar.root Mode mHcut 
#./skimtree dir Hamb mc TW.root Mode mHcut 
#./skimtree dir Hamb mc WJetsMG.root Mode mHcut 
#./skimtree dir Hamb mc WW.root Mode mHcut 
#./skimtree dir Hamb mc WZ.root Mode mHcut 
#./skimtree dir Hamb mc ZZ.root Mode mHcut 
./skimtree dir Hamb mc DYMG1J10To50.root  Mode mHcut 
./skimtree dir Hamb mc DYMG1J50.root  Mode mHcut
./skimtree dir Hamb mc DYMG2J10To50.root  Mode mHcut 
./skimtree dir Hamb mc DYMG2J50.root  Mode mHcut 
./skimtree dir Hamb mc DYMG3J10To50.root  Mode mHcut 
./skimtree dir Hamb mc DYMG3J50.root  Mode mHcut 
./skimtree dir Hamb mc DYMG4J10To50.root  Mode mHcut 
./skimtree dir Hamb mc DYMG4J50.root  Mode mHcut 
./skimtree dir Hamb mc DYMGInclusive10To50.root  Mode mHcut 
./skimtree dir Hamb mc DYMGInclusive50Ext1.root  Mode mHcut 
./skimtree dir Hamb mc DYMGInclusive50Ext2.root  Mode mHcut 
